### PR TITLE
Allow usage of SSO credentials

### PR DESCRIPTION
**Pull request by vecchp**
Heya, thanks for making this useful tool! 

We wanted to use `ssm-get-parameter` to inject secrets during local development.  Unfortunately it didn't seem to work out of the box with AWS SSO.  This change should result `ssm-get-paramater` to behavior similar to to the AWS cli where it follows a credential chain.  I referenced the article [AWS SSO Support in the AWS SDK for Go](https://aws.amazon.com/blogs/developer/aws-sso-support-in-the-aws-sdk-for-go/#:~:text=The%20AWS%20SSO%20credential%20provider,using%20the%20AWS%20CLI%20v2.) for the required changes.

With the above change and setting the `AWS_REGION` & `AWS_PROFILE` environment variables I was able to pull in the secret.

Side note:
I'm not very familiar with deps in go. I think i upgraded to the latest versions of the pulled in dependencies.  I also think I properly updated the vendor folder as well.

### CODE REVIEW

**Comment by vecchp** [comment]
@mvanholsteijn checking in to see if there is anything that needs to be done to get this merged.

**Comment by mvanholsteijn** [comment]
Hi Paul,

Thank you for you pr! I am currently on holiday, but will merge your
request when i get back in the 3rd week of august.

Cheers,  Mark

**Comment by vecchp** [comment]
Heya checking in again now that it is early September.

**Comment by mvanholsteijn** [comment]
Thanks for the reminder @vecchp ! I merged and pushed your changes to version 0.4.0; The binaries should appear any minute now

**Comment by vecchp** [comment]
Thanks!

**Pull request merged**
